--<ScriptOptions statementTerminator=";"/>

DROP TRIGGER OBS_TRIGGER;

DROP TRIGGER CON_ALERT;

DROP TRIGGER WEIGHT_TRIGGER;

DROP TRIGGER OS_TRIGGER;

DROP TRIGGER CON_TRIGGER;

DROP TRIGGER EXERCISE_TRIGGER;

DROP TRIGGER T_TRIGGER;

DROP TRIGGER OS_ALERT;

DROP TRIGGER M_TRIGGER;

DROP TRIGGER HF_TRIGGER;

DROP TRIGGER TEMP_ALERT;

DROP TRIGGER PATIENT_INCREMENT_TRIGGER;

DROP TRIGGER PAIN_ALERT;

DROP TRIGGER HP_TRIGGER;

DROP TRIGGER BP_TRIGGER;

DROP TRIGGER PAIN_TRIGGER;

DROP TRIGGER BP_DIA_ALERT;

DROP TRIGGER BP_SYS_ALERT;

DROP TRIGGER DIET_TRIGGER;

DROP TRIGGER ET_TRIGGER;

DROP TRIGGER TEST_TRIGGER;

ALTER TABLE OXYGENSATURATION DROP CONSTRAINT SYS_C00349801;

ALTER TABLE WATER_CONSUMPTION_TYPE DROP CONSTRAINT SYS_C00352331;

ALTER TABLE PATIENT_BELONGS_TO_CLASS DROP CONSTRAINT SYS_C00351834;

ALTER TABLE DIET DROP CONSTRAINT SYS_C00349810;

ALTER TABLE PAIN DROP CONSTRAINT SYS_C00349836;

ALTER TABLE MOOD DROP CONSTRAINT SYS_C00350032;

ALTER TABLE WATER_CONSUMPTION_TYPE DROP CONSTRAINT SYS_C00352332;

ALTER TABLE EXERCISETOLERANCE DROP CONSTRAINT SYS_C00350021;

ALTER TABLE BLOODPRESSURE DROP CONSTRAINT SYS_C00349817;

ALTER TABLE OBSERVATIONS DROP CONSTRAINT SYS_C00349556;

ALTER TABLE HEART_RATE_TYPE DROP CONSTRAINT SYS_C00352329;

ALTER TABLE BLOODPRESSURE DROP CONSTRAINT SYS_C00349816;

ALTER TABLE CONTRACTION DROP CONSTRAINT SYS_C00349825;

ALTER TABLE CONTRACTION DROP CONSTRAINT SYS_C00349824;

ALTER TABLE EXERCISETOLERANCE DROP CONSTRAINT SYS_C00350022;

ALTER TABLE MESSAGES DROP CONSTRAINT SYS_C00367502;

ALTER TABLE BOOYA_TYPE DROP CONSTRAINT SYS_C00364016;

ALTER TABLE OXYGENSATURATION DROP CONSTRAINT SYS_C00349802;

ALTER TABLE EXERCISE DROP CONSTRAINT SYS_C00349855;

ALTER TABLE TYPE_BELONGS_TO_CLASS DROP CONSTRAINT SYS_C00351956;

ALTER TABLE PULSE_TYPE DROP CONSTRAINT SYS_C00352325;

ALTER TABLE TAKES DROP CONSTRAINT SYS_C00342556;

ALTER TABLE MOOD DROP CONSTRAINT SYS_C00350031;

ALTER TABLE TEMPERATURE DROP CONSTRAINT SYS_C00349707;

ALTER TABLE PATIENT_BELONGS_TO_CLASS DROP CONSTRAINT SYS_C00351835;

ALTER TABLE PAIN DROP CONSTRAINT SYS_C00349835;

ALTER TABLE HEALTHFRIENDS DROP CONSTRAINT SYS_C00350045;

ALTER TABLE TYPE_BELONGS_TO_CLASS DROP CONSTRAINT SYS_C00351957;

ALTER TABLE MESSAGES DROP CONSTRAINT SYS_C00367501;

ALTER TABLE RESERVES DROP CONSTRAINT SYS_C00345532;

ALTER TABLE DIET DROP CONSTRAINT SYS_C00349811;

ALTER TABLE TEACHES DROP CONSTRAINT SYS_C00342559;

ALTER TABLE WEIGHT DROP CONSTRAINT SYS_C00349844;

ALTER TABLE HEALTHFRIENDS DROP CONSTRAINT SYS_C00350044;

ALTER TABLE TEACHES DROP CONSTRAINT SYS_C00342558;

ALTER TABLE ALERTS DROP CONSTRAINT SYS_C00366741;

ALTER TABLE BOOYA_TYPE DROP CONSTRAINT SYS_C00364017;

ALTER TABLE TEMPERATURE DROP CONSTRAINT SYS_C00349708;

ALTER TABLE TAKES DROP CONSTRAINT SYS_C00342555;

ALTER TABLE PULSE_TYPE DROP CONSTRAINT SYS_C00352324;

ALTER TABLE OBSERVATIONTYPE DROP CONSTRAINT SYS_C00349323;

ALTER TABLE HEALTHFRIENDS DROP CONSTRAINT SYS_C00350043;

ALTER TABLE EXERCISE DROP CONSTRAINT SYS_C00349856;

ALTER TABLE OBSERVATIONS DROP CONSTRAINT SYS_C00349557;

ALTER TABLE CATALOG DROP CONSTRAINT SYS_C00345925;

ALTER TABLE ALERTS DROP CONSTRAINT PID_FOREIGNKEY;

ALTER TABLE WEIGHT DROP CONSTRAINT SYS_C00349845;

ALTER TABLE HEART_RATE_TYPE DROP CONSTRAINT SYS_C00352328;

ALTER TABLE CATALOG DROP CONSTRAINT SYS_C00345924;

ALTER TABLE HEALTHPROFESSIONALS DROP CONSTRAINT SYS_C00350036;

ALTER TABLE RESERVES DROP CONSTRAINT SYS_C00345531;

ALTER TABLE HEALTHPROFESSIONALS DROP CONSTRAINT SYS_C00350035;

ALTER TABLE TAKES DROP CONSTRAINT SYS_C00342554;

ALTER TABLE WEIGHT DROP CONSTRAINT SYS_C00349843;

ALTER TABLE TEMPERATURE DROP CONSTRAINT SYS_C00349706;

ALTER TABLE COURSE DROP CONSTRAINT SYS_C00342553;

ALTER TABLE STUDENT DROP CONSTRAINT SYS_C00342552;

ALTER TABLE EXERCISETOLERANCE DROP CONSTRAINT SYS_C00350020;

ALTER TABLE PATIENTS DROP CONSTRAINT SYS_C00349432;

ALTER TABLE PATIENTCLASS DROP CONSTRAINT SYS_C00349269;

ALTER TABLE CONTRACTION DROP CONSTRAINT SYS_C00349823;

ALTER TABLE TYPE_BELONGS_TO_CLASS DROP CONSTRAINT SYS_C00351955;

ALTER TABLE OXYGENSATURATION DROP CONSTRAINT SYS_C00349800;

ALTER TABLE WATER_CONSUMPTION_TYPE DROP CONSTRAINT SYS_C00352330;

ALTER TABLE SUUPLIERS DROP CONSTRAINT SYS_C00345918;

ALTER TABLE MESSAGES DROP CONSTRAINT SYS_C00367500;

ALTER TABLE DIET DROP CONSTRAINT SYS_C00349809;

ALTER TABLE OBSERVATIONCATEGORY DROP CONSTRAINT SYS_C00349271;

ALTER TABLE PROFESSOR DROP CONSTRAINT SYS_C00342557;

ALTER TABLE CATALOG DROP CONSTRAINT SYS_C00345923;

ALTER TABLE TEST DROP CONSTRAINT SYS_C00350587;

ALTER TABLE HEALTHSUPPORTERS DROP CONSTRAINT SYS_C00350033;

ALTER TABLE PAIN DROP CONSTRAINT SYS_C00349834;

ALTER TABLE OBSERVATIONS DROP CONSTRAINT SYS_C00349555;

ALTER TABLE BOATS DROP CONSTRAINT SYS_C00345513;

ALTER TABLE PATIENT_BELONGS_TO_CLASS DROP CONSTRAINT SYS_C00351833;

ALTER TABLE ALERTS DROP CONSTRAINT SYS_C00366740;

ALTER TABLE PULSE_TYPE DROP CONSTRAINT SYS_C00352323;

ALTER TABLE OBSERVATIONTYPE DROP CONSTRAINT SYS_C00349322;

ALTER TABLE MOOD DROP CONSTRAINT SYS_C00350030;

ALTER TABLE BLOODPRESSURE DROP CONSTRAINT SYS_C00349815;

ALTER TABLE BOOYA_TYPE DROP CONSTRAINT SYS_C00364015;

ALTER TABLE HEALTHFRIENDS DROP CONSTRAINT SYS_C00350042;

ALTER TABLE EXERCISE DROP CONSTRAINT SYS_C00349854;

ALTER TABLE HEART_RATE_TYPE DROP CONSTRAINT SYS_C00352327;

ALTER TABLE RESERVES DROP CONSTRAINT SYS_C00345530;

ALTER TABLE PARTS DROP CONSTRAINT SYS_C00345919;

ALTER TABLE SAILORS DROP CONSTRAINT SYS_C00345512;

DROP TABLE TAKES;

DROP TABLE BOATS;

DROP TABLE TEMPERATURE;

DROP TABLE MOOD;

DROP TABLE WEIGHT;

DROP TABLE TEST;

DROP TABLE TEACHES;

DROP TABLE PROJECTS;

DROP TABLE BLOODPRESSURE;

DROP TABLE PATIENTCLASS;

DROP TABLE EXERCISE;

DROP TABLE RESERVES;

DROP TABLE CATALOG;

DROP TABLE ALERTS;

DROP TABLE DEMO;

DROP TABLE OBSERVATIONCATEGORY;

DROP TABLE HEART_RATE_TYPE;

DROP TABLE OXYGENSATURATION;

DROP TABLE HEALTHSUPPORTERS;

DROP TABLE PATIENTS;

DROP TABLE BATTLES;

DROP TABLE STUDENT;

DROP TABLE SAILORS;

DROP TABLE SUUPLIERS;

DROP TABLE MESSAGES;

DROP TABLE PATIENT_BELONGS_TO_CLASS;

DROP TABLE PAIN;

DROP TABLE DIET;

DROP TABLE OBSERVATIONTYPE;

DROP TABLE CONTRACTION;

DROP TABLE EXERCISETOLERANCE;

DROP TABLE WATER_CONSUMPTION_TYPE;

DROP TABLE TYPE_BELONGS_TO_CLASS;

DROP TABLE SHIPS;

DROP TABLE HEALTHFRIENDS;

DROP TABLE COFFEES;

DROP TABLE COURSE;

DROP TABLE PARTS;

DROP TABLE HEALTHPROFESSIONALS;

DROP TABLE BOOYA_TYPE;

DROP TABLE PROFESSOR;

DROP TABLE TIME_DEMO;

DROP TABLE PULSE_TYPE;

DROP TABLE OBSERVATIONS;

CREATE TABLE TAKES (
		SID NUMBER NOT NULL,
		GRADE VARCHAR2(20),
		CID VARCHAR2(20) NOT NULL
	);

CREATE TABLE BOATS (
		BID NUMBER(9 , 0) NOT NULL,
		BNAME VARCHAR2(30),
		COLOR VARCHAR2(30)
	);

CREATE TABLE TEMPERATURE (
		T_ID NUMBER NOT NULL,
		T_AMT FLOAT(63),
		OB_ID NUMBER NOT NULL,
		OT_ID NUMBER
	);

CREATE TABLE MOOD (
		M_ID NUMBER NOT NULL,
		M_VALUE VARCHAR2(30),
		OB_ID NUMBER NOT NULL,
		OT_ID NUMBER
	);

CREATE TABLE WEIGHT (
		W_ID NUMBER NOT NULL,
		W_AMT FLOAT(63),
		OB_ID NUMBER NOT NULL,
		OT_ID NUMBER
	);

CREATE TABLE TEST (
		ID NUMBER NOT NULL,
		NAME VARCHAR2(30)
	);

CREATE TABLE TEACHES (
		FID NUMBER,
		CID VARCHAR2(20)
	);

CREATE TABLE PROJECTS (
		JID NUMBER,
		JNAME VARCHAR2(30),
		DEPTID NUMBER
	);

CREATE TABLE BLOODPRESSURE (
		BP_ID NUMBER NOT NULL,
		BP_SYS NUMBER,
		BP_DIA NUMBER,
		OB_ID NUMBER NOT NULL,
		OT_ID NUMBER
	);

CREATE TABLE PATIENTCLASS (
		PC_ID NUMBER NOT NULL,
		PC_NAME VARCHAR2(30)
	);

CREATE TABLE EXERCISE (
		E_ID NUMBER NOT NULL,
		E_KIND VARCHAR2(500),
		E_DURATION FLOAT(63),
		OB_ID NUMBER NOT NULL,
		OT_ID NUMBER
	);

CREATE TABLE RESERVES (
		SID NUMBER(4 , 0) NOT NULL,
		BID NUMBER(4 , 0) NOT NULL,
		DAY DATE NOT NULL
	);

CREATE TABLE CATALOG (
		SID NUMBER NOT NULL,
		PID NUMBER NOT NULL,
		JID NUMBER,
		COST NUMBER
	);

CREATE TABLE ALERTS (
		A_ID NUMBER NOT NULL,
		OB_ID NUMBER,
		ENT_VAL VARCHAR2(100),
		THR_VAL VARCHAR2(100),
		ALERT_VIEWED VARCHAR2(1),
		PID NUMBER
	);

CREATE TABLE DEMO (
		A NUMBER
	);

CREATE TABLE OBSERVATIONCATEGORY (
		OC_ID NUMBER NOT NULL,
		OC_NAME VARCHAR2(30)
	);

CREATE TABLE HEART_RATE_TYPE (
		HEART_RATE_ID NUMBER NOT NULL,
		FREQUENCY VARCHAR2(30),
		OB_ID NUMBER NOT NULL,
		OT_ID NUMBER
	);

CREATE TABLE OXYGENSATURATION (
		OT_ID NUMBER,
		OB_ID NUMBER NOT NULL,
		OS_ID NUMBER NOT NULL,
		OS_AMT FLOAT(63)
	);

CREATE TABLE HEALTHSUPPORTERS (
		HS_ID NUMBER NOT NULL,
		HS_TYPE VARCHAR2(100)
	);

CREATE TABLE PATIENTS (
		PID NUMBER NOT NULL,
		PNAME VARCHAR2(30),
		PDOB DATE,
		PSEX VARCHAR2(1),
		P_PUBSTATUS VARCHAR2(1),
		P_PASSWORD VARCHAR2(100),
		P_STREET VARCHAR2(500),
		P_CITY VARCHAR2(50),
		P_STATE VARCHAR2(100),
		P_COUNTRY VARCHAR2(100),
		P_ZIPCODE NUMBER,
		P_AGE NUMBER,
		PATIENTID VARCHAR2(30)
	);

CREATE TABLE BATTLES (
		SHIP VARCHAR2(20),
		BATTLENAME VARCHAR2(50),
		RESULT VARCHAR2(30)
	);

CREATE TABLE STUDENT (
		SID NUMBER NOT NULL,
		NAME VARCHAR2(20)
	);

CREATE TABLE SAILORS (
		SID NUMBER(9 , 0) NOT NULL,
		SNAME VARCHAR2(30),
		RATING NUMBER(2 , 0),
		AGE NUMBER(4 , 1)
	);

CREATE TABLE SUUPLIERS (
		SID NUMBER NOT NULL,
		SNAME VARCHAR2(20),
		ADDRESS VARCHAR2(40)
	);

CREATE TABLE MESSAGES (
		MESSAGE_ID NUMBER NOT NULL,
		SENDER_PID NUMBER,
		RECEIVER_PID NUMBER,
		MESSAGE VARCHAR2(300),
		MESSAGE_VIEWED VARCHAR2(3)
	);

CREATE TABLE PATIENT_BELONGS_TO_CLASS (
		PID NUMBER NOT NULL,
		PC_ID NUMBER NOT NULL
	);

CREATE TABLE PAIN (
		PAIN_ID NUMBER NOT NULL,
		PAIN_SCALE NUMBER,
		OB_ID NUMBER NOT NULL,
		OT_ID NUMBER
	);

CREATE TABLE DIET (
		OT_ID NUMBER,
		OB_ID NUMBER NOT NULL,
		D_ID NUMBER NOT NULL,
		D_ITEM VARCHAR2(1000),
		D_QTY FLOAT(63)
	);

CREATE TABLE OBSERVATIONTYPE (
		OT_ID NUMBER NOT NULL,
		OT_NAME VARCHAR2(30),
		OC_ID NUMBER
	);

CREATE TABLE CONTRACTION (
		CON_ID NUMBER NOT NULL,
		CON_FREQUENCY FLOAT(63),
		OB_ID NUMBER NOT NULL,
		OT_ID NUMBER
	);

CREATE TABLE EXERCISETOLERANCE (
		ET_ID NUMBER NOT NULL,
		ET_NUMEX FLOAT(63),
		OB_ID NUMBER NOT NULL,
		OT_ID NUMBER
	);

CREATE TABLE WATER_CONSUMPTION_TYPE (
		WATER_CONSUMPTION_ID NUMBER NOT NULL,
		NUMBER_OF_LITRES VARCHAR2(30),
		OB_ID NUMBER NOT NULL,
		OT_ID NUMBER
	);

CREATE TABLE TYPE_BELONGS_TO_CLASS (
		OT_ID NUMBER NOT NULL,
		PC_ID NUMBER NOT NULL
	);

CREATE TABLE SHIPS (
		NAME VARCHAR2(20),
		YEAR NUMBER,
		COUNTRY VARCHAR2(30),
		NUMGUNS NUMBER,
		GUNSIZE NUMBER,
		DISPLACEMENT NUMBER
	);

CREATE TABLE HEALTHFRIENDS (
		HF_ID NUMBER NOT NULL,
		PID_1 NUMBER NOT NULL,
		PID_2 NUMBER NOT NULL,
		HF_DT DATE,
		HS_ID NUMBER
	);

CREATE TABLE COFFEES (
		COF_NAME VARCHAR2(32),
		SUP_ID NUMBER,
		PRICE FLOAT(126),
		SALES NUMBER,
		TOTAL NUMBER
	);

CREATE TABLE COURSE (
		CID VARCHAR2(20) NOT NULL,
		SUBJ VARCHAR2(20),
		SEM VARCHAR2(20)
	);

CREATE TABLE PARTS (
		PID NUMBER NOT NULL,
		PNAME VARCHAR2(30),
		COLOR VARCHAR2(20)
	);

CREATE TABLE HEALTHPROFESSIONALS (
		HP_ID NUMBER NOT NULL,
		HP_TYPE VARCHAR2(50),
		HP_NAME VARCHAR2(100),
		HP_CLINIC VARCHAR2(100),
		HS_ID NUMBER,
		HP_PASSWORD VARCHAR2(100),
		HEALTHPROID VARCHAR2(30)
	);

CREATE TABLE BOOYA_TYPE (
		BOOYA_ID NUMBER NOT NULL,
		HEYA VARCHAR2(30),
		OB_ID NUMBER NOT NULL,
		OT_ID NUMBER
	);

CREATE TABLE PROFESSOR (
		FID NUMBER NOT NULL,
		NAME VARCHAR2(20)
	);

CREATE TABLE TIME_DEMO (
		ONLY_DATE TIMESTAMP
	);

CREATE TABLE PULSE_TYPE (
		PULSE_ID NUMBER NOT NULL,
		FREQUENCY VARCHAR2(30),
		OB_ID NUMBER NOT NULL,
		OT_ID NUMBER
	);

CREATE TABLE OBSERVATIONS (
		OB_ID NUMBER NOT NULL,
		PID NUMBER,
		OT_ID NUMBER,
		OB_DTO TIMESTAMP,
		OB_DTR TIMESTAMP
	);

ALTER TABLE HEALTHPROFESSIONALS ADD CONSTRAINT SYS_C00350035 PRIMARY KEY (HP_ID);

ALTER TABLE TAKES ADD CONSTRAINT SYS_C00342554 PRIMARY KEY (SID, CID);

ALTER TABLE WEIGHT ADD CONSTRAINT SYS_C00349843 PRIMARY KEY (W_ID, OB_ID);

ALTER TABLE TEMPERATURE ADD CONSTRAINT SYS_C00349706 PRIMARY KEY (T_ID, OB_ID);

ALTER TABLE COURSE ADD CONSTRAINT SYS_C00342553 PRIMARY KEY (CID);

ALTER TABLE STUDENT ADD CONSTRAINT SYS_C00342552 PRIMARY KEY (SID);

ALTER TABLE EXERCISETOLERANCE ADD CONSTRAINT SYS_C00350020 PRIMARY KEY (ET_ID, OB_ID);

ALTER TABLE PATIENTS ADD CONSTRAINT SYS_C00349432 PRIMARY KEY (PID);

ALTER TABLE PATIENTCLASS ADD CONSTRAINT SYS_C00349269 PRIMARY KEY (PC_ID);

ALTER TABLE CONTRACTION ADD CONSTRAINT SYS_C00349823 PRIMARY KEY (CON_ID, OB_ID);

ALTER TABLE TYPE_BELONGS_TO_CLASS ADD CONSTRAINT SYS_C00351955 PRIMARY KEY (OT_ID, PC_ID);

ALTER TABLE OXYGENSATURATION ADD CONSTRAINT SYS_C00349800 PRIMARY KEY (OS_ID, OB_ID);

ALTER TABLE WATER_CONSUMPTION_TYPE ADD CONSTRAINT SYS_C00352330 PRIMARY KEY (WATER_CONSUMPTION_ID, OB_ID);

ALTER TABLE SUUPLIERS ADD CONSTRAINT SYS_C00345918 PRIMARY KEY (SID);

ALTER TABLE MESSAGES ADD CONSTRAINT SYS_C00367500 PRIMARY KEY (MESSAGE_ID);

ALTER TABLE DIET ADD CONSTRAINT SYS_C00349809 PRIMARY KEY (D_ID, OB_ID);

ALTER TABLE OBSERVATIONCATEGORY ADD CONSTRAINT SYS_C00349271 PRIMARY KEY (OC_ID);

ALTER TABLE PROFESSOR ADD CONSTRAINT SYS_C00342557 PRIMARY KEY (FID);

ALTER TABLE CATALOG ADD CONSTRAINT SYS_C00345923 PRIMARY KEY (SID, PID);

ALTER TABLE TEST ADD CONSTRAINT SYS_C00350587 PRIMARY KEY (ID);

ALTER TABLE HEALTHSUPPORTERS ADD CONSTRAINT SYS_C00350033 PRIMARY KEY (HS_ID);

ALTER TABLE PAIN ADD CONSTRAINT SYS_C00349834 PRIMARY KEY (PAIN_ID, OB_ID);

ALTER TABLE OBSERVATIONS ADD CONSTRAINT SYS_C00349555 PRIMARY KEY (OB_ID);

ALTER TABLE BOATS ADD CONSTRAINT SYS_C00345513 PRIMARY KEY (BID);

ALTER TABLE PATIENT_BELONGS_TO_CLASS ADD CONSTRAINT SYS_C00351833 PRIMARY KEY (PID, PC_ID);

ALTER TABLE ALERTS ADD CONSTRAINT SYS_C00366740 PRIMARY KEY (A_ID);

ALTER TABLE PULSE_TYPE ADD CONSTRAINT SYS_C00352323 PRIMARY KEY (PULSE_ID, OB_ID);

ALTER TABLE OBSERVATIONTYPE ADD CONSTRAINT SYS_C00349322 PRIMARY KEY (OT_ID);

ALTER TABLE MOOD ADD CONSTRAINT SYS_C00350030 PRIMARY KEY (M_ID, OB_ID);

ALTER TABLE BLOODPRESSURE ADD CONSTRAINT SYS_C00349815 PRIMARY KEY (BP_ID, OB_ID);

ALTER TABLE BOOYA_TYPE ADD CONSTRAINT SYS_C00364015 PRIMARY KEY (BOOYA_ID, OB_ID);

ALTER TABLE HEALTHFRIENDS ADD CONSTRAINT SYS_C00350042 PRIMARY KEY (HF_ID, PID_1, PID_2);

ALTER TABLE EXERCISE ADD CONSTRAINT SYS_C00349854 PRIMARY KEY (E_ID, OB_ID);

ALTER TABLE HEART_RATE_TYPE ADD CONSTRAINT SYS_C00352327 PRIMARY KEY (HEART_RATE_ID, OB_ID);

ALTER TABLE RESERVES ADD CONSTRAINT SYS_C00345530 PRIMARY KEY (SID, BID, DAY);

ALTER TABLE PARTS ADD CONSTRAINT SYS_C00345919 PRIMARY KEY (PID);

ALTER TABLE SAILORS ADD CONSTRAINT SYS_C00345512 PRIMARY KEY (SID);

ALTER TABLE OXYGENSATURATION ADD CONSTRAINT SYS_C00349801 FOREIGN KEY (OB_ID)
	REFERENCES OBSERVATIONS (OB_ID);

ALTER TABLE WATER_CONSUMPTION_TYPE ADD CONSTRAINT SYS_C00352331 FOREIGN KEY (OB_ID)
	REFERENCES OBSERVATIONS (OB_ID);

ALTER TABLE PATIENT_BELONGS_TO_CLASS ADD CONSTRAINT SYS_C00351834 FOREIGN KEY (PID)
	REFERENCES PATIENTS (PID);

ALTER TABLE DIET ADD CONSTRAINT SYS_C00349810 FOREIGN KEY (OB_ID)
	REFERENCES OBSERVATIONS (OB_ID);

ALTER TABLE PAIN ADD CONSTRAINT SYS_C00349836 FOREIGN KEY (OT_ID)
	REFERENCES OBSERVATIONTYPE (OT_ID);

ALTER TABLE MOOD ADD CONSTRAINT SYS_C00350032 FOREIGN KEY (OT_ID)
	REFERENCES OBSERVATIONTYPE (OT_ID);

ALTER TABLE WATER_CONSUMPTION_TYPE ADD CONSTRAINT SYS_C00352332 FOREIGN KEY (OT_ID)
	REFERENCES OBSERVATIONTYPE (OT_ID);

ALTER TABLE EXERCISETOLERANCE ADD CONSTRAINT SYS_C00350021 FOREIGN KEY (OB_ID)
	REFERENCES OBSERVATIONS (OB_ID);

ALTER TABLE BLOODPRESSURE ADD CONSTRAINT SYS_C00349817 FOREIGN KEY (OT_ID)
	REFERENCES OBSERVATIONTYPE (OT_ID);

ALTER TABLE OBSERVATIONS ADD CONSTRAINT SYS_C00349556 FOREIGN KEY (PID)
	REFERENCES PATIENTS (PID);

ALTER TABLE HEART_RATE_TYPE ADD CONSTRAINT SYS_C00352329 FOREIGN KEY (OT_ID)
	REFERENCES OBSERVATIONTYPE (OT_ID);

ALTER TABLE BLOODPRESSURE ADD CONSTRAINT SYS_C00349816 FOREIGN KEY (OB_ID)
	REFERENCES OBSERVATIONS (OB_ID);

ALTER TABLE CONTRACTION ADD CONSTRAINT SYS_C00349825 FOREIGN KEY (OT_ID)
	REFERENCES OBSERVATIONTYPE (OT_ID);

ALTER TABLE CONTRACTION ADD CONSTRAINT SYS_C00349824 FOREIGN KEY (OB_ID)
	REFERENCES OBSERVATIONS (OB_ID);

ALTER TABLE EXERCISETOLERANCE ADD CONSTRAINT SYS_C00350022 FOREIGN KEY (OT_ID)
	REFERENCES OBSERVATIONTYPE (OT_ID);

ALTER TABLE MESSAGES ADD CONSTRAINT SYS_C00367502 FOREIGN KEY (RECEIVER_PID)
	REFERENCES PATIENTS (PID);

ALTER TABLE BOOYA_TYPE ADD CONSTRAINT SYS_C00364016 FOREIGN KEY (OB_ID)
	REFERENCES OBSERVATIONS (OB_ID);

ALTER TABLE OXYGENSATURATION ADD CONSTRAINT SYS_C00349802 FOREIGN KEY (OT_ID)
	REFERENCES OBSERVATIONTYPE (OT_ID);

ALTER TABLE EXERCISE ADD CONSTRAINT SYS_C00349855 FOREIGN KEY (OB_ID)
	REFERENCES OBSERVATIONS (OB_ID);

ALTER TABLE TYPE_BELONGS_TO_CLASS ADD CONSTRAINT SYS_C00351956 FOREIGN KEY (OT_ID)
	REFERENCES OBSERVATIONTYPE (OT_ID);

ALTER TABLE PULSE_TYPE ADD CONSTRAINT SYS_C00352325 FOREIGN KEY (OT_ID)
	REFERENCES OBSERVATIONTYPE (OT_ID);

ALTER TABLE TAKES ADD CONSTRAINT SYS_C00342556 FOREIGN KEY (CID)
	REFERENCES COURSE (CID);

ALTER TABLE MOOD ADD CONSTRAINT SYS_C00350031 FOREIGN KEY (OB_ID)
	REFERENCES OBSERVATIONS (OB_ID);

ALTER TABLE TEMPERATURE ADD CONSTRAINT SYS_C00349707 FOREIGN KEY (OB_ID)
	REFERENCES OBSERVATIONS (OB_ID);

ALTER TABLE PATIENT_BELONGS_TO_CLASS ADD CONSTRAINT SYS_C00351835 FOREIGN KEY (PC_ID)
	REFERENCES PATIENTCLASS (PC_ID);

ALTER TABLE PAIN ADD CONSTRAINT SYS_C00349835 FOREIGN KEY (OB_ID)
	REFERENCES OBSERVATIONS (OB_ID);

ALTER TABLE HEALTHFRIENDS ADD CONSTRAINT SYS_C00350045 FOREIGN KEY (HS_ID)
	REFERENCES HEALTHSUPPORTERS (HS_ID);

ALTER TABLE TYPE_BELONGS_TO_CLASS ADD CONSTRAINT SYS_C00351957 FOREIGN KEY (PC_ID)
	REFERENCES PATIENTCLASS (PC_ID);

ALTER TABLE MESSAGES ADD CONSTRAINT SYS_C00367501 FOREIGN KEY (SENDER_PID)
	REFERENCES PATIENTS (PID);

ALTER TABLE RESERVES ADD CONSTRAINT SYS_C00345532 FOREIGN KEY (BID)
	REFERENCES BOATS (BID);

ALTER TABLE DIET ADD CONSTRAINT SYS_C00349811 FOREIGN KEY (OT_ID)
	REFERENCES OBSERVATIONTYPE (OT_ID);

ALTER TABLE TEACHES ADD CONSTRAINT SYS_C00342559 FOREIGN KEY (CID)
	REFERENCES COURSE (CID);

ALTER TABLE WEIGHT ADD CONSTRAINT SYS_C00349844 FOREIGN KEY (OB_ID)
	REFERENCES OBSERVATIONS (OB_ID);

ALTER TABLE HEALTHFRIENDS ADD CONSTRAINT SYS_C00350044 FOREIGN KEY (PID_2)
	REFERENCES PATIENTS (PID);

ALTER TABLE TEACHES ADD CONSTRAINT SYS_C00342558 FOREIGN KEY (FID)
	REFERENCES PROFESSOR (FID);

ALTER TABLE ALERTS ADD CONSTRAINT SYS_C00366741 FOREIGN KEY (OB_ID)
	REFERENCES OBSERVATIONS (OB_ID);

ALTER TABLE BOOYA_TYPE ADD CONSTRAINT SYS_C00364017 FOREIGN KEY (OT_ID)
	REFERENCES OBSERVATIONTYPE (OT_ID);

ALTER TABLE TEMPERATURE ADD CONSTRAINT SYS_C00349708 FOREIGN KEY (OT_ID)
	REFERENCES OBSERVATIONTYPE (OT_ID);

ALTER TABLE TAKES ADD CONSTRAINT SYS_C00342555 FOREIGN KEY (SID)
	REFERENCES STUDENT (SID);

ALTER TABLE PULSE_TYPE ADD CONSTRAINT SYS_C00352324 FOREIGN KEY (OB_ID)
	REFERENCES OBSERVATIONS (OB_ID);

ALTER TABLE OBSERVATIONTYPE ADD CONSTRAINT SYS_C00349323 FOREIGN KEY (OC_ID)
	REFERENCES OBSERVATIONCATEGORY (OC_ID);

ALTER TABLE HEALTHFRIENDS ADD CONSTRAINT SYS_C00350043 FOREIGN KEY (PID_1)
	REFERENCES PATIENTS (PID);

ALTER TABLE EXERCISE ADD CONSTRAINT SYS_C00349856 FOREIGN KEY (OT_ID)
	REFERENCES OBSERVATIONTYPE (OT_ID);

ALTER TABLE OBSERVATIONS ADD CONSTRAINT SYS_C00349557 FOREIGN KEY (OT_ID)
	REFERENCES OBSERVATIONTYPE (OT_ID);

ALTER TABLE CATALOG ADD CONSTRAINT SYS_C00345925 FOREIGN KEY (PID)
	REFERENCES PARTS (PID);

ALTER TABLE ALERTS ADD CONSTRAINT PID_FOREIGNKEY FOREIGN KEY (PID)
	REFERENCES PATIENTS (PID);

ALTER TABLE WEIGHT ADD CONSTRAINT SYS_C00349845 FOREIGN KEY (OT_ID)
	REFERENCES OBSERVATIONTYPE (OT_ID);

ALTER TABLE HEART_RATE_TYPE ADD CONSTRAINT SYS_C00352328 FOREIGN KEY (OB_ID)
	REFERENCES OBSERVATIONS (OB_ID);

ALTER TABLE CATALOG ADD CONSTRAINT SYS_C00345924 FOREIGN KEY (SID)
	REFERENCES SUUPLIERS (SID);

ALTER TABLE HEALTHPROFESSIONALS ADD CONSTRAINT SYS_C00350036 FOREIGN KEY (HS_ID)
	REFERENCES HEALTHSUPPORTERS (HS_ID);

ALTER TABLE RESERVES ADD CONSTRAINT SYS_C00345531 FOREIGN KEY (SID)
	REFERENCES SAILORS (SID);

CREATE TRIGGER OBS_TRIGGER BEFORE INSERT ON OBSERVATIONS
FOR EACH ROW
BEGIN
SELECT obs_sequence.nextval INTO :NEW.ob_id FROM dual;
END;

CREATE TRIGGER CON_ALERT BEFORE INSERT ON CONTRACTION
FOR EACH ROW
declare pid number;
begin
select o.pid into pid from observations o where o.ob_id=:new.ob_id;
if(:new.con_frequency*2>4)then
insert into alerts values(alerts_sequence.nextval,:new.ob_id,'contraction frequency','4','n',pid);
end if;
end;

CREATE TRIGGER WEIGHT_TRIGGER BEFORE INSERT ON WEIGHT
FOR EACH ROW
BEGIN
SELECT weight_sequence.nextval INTO :NEW.w_id FROM DUAL;
END;

CREATE TRIGGER OS_TRIGGER BEFORE INSERT ON OXYGENSATURATION
FOR EACH ROW
begin
select os_sequence.nextval INTO :NEW.os_id FROM dual;
end;

CREATE TRIGGER CON_TRIGGER BEFORE INSERT ON CONTRACTION
FOR EACH ROW
BEGIN
SELECT con_sequence.nextval INTO :NEW.con_id FROM dual;
END;

CREATE TRIGGER EXERCISE_TRIGGER BEFORE INSERT ON EXERCISE
FOR EACH ROW
BEGIN
SELECT exercise_sequence.nextval INTO :NEW.e_id FROM DUAL;
END;

CREATE TRIGGER T_TRIGGER BEFORE INSERT ON TEMPERATURE
FOR EACH ROW
BEGIN
SELECT t_sequence.nextval INTO :NEW.t_id FROM dual;
END;

CREATE TRIGGER OS_ALERT BEFORE INSERT ON OXYGENSATURATION
FOR EACH ROW
declare pid number;
begin
select o.pid into pid from observations o where o.ob_id=:new.ob_id;
if(:new.os_amt<88)then
insert into alerts values(alerts_sequence.nextval,:new.ob_id,'oxygensaturation','88','n',pid);
end if;
end;

CREATE TRIGGER M_TRIGGER BEFORE INSERT ON MOOD
FOR EACH ROW
BEGIN
SELECT m_sequence.nextval INTO :NEW.m_id FROM dual;
END;

CREATE TRIGGER HF_TRIGGER BEFORE INSERT ON HEALTHFRIENDS
FOR EACH ROW
begin
select hf_sequence.nextval into :new.hf_id from dual;
end;

CREATE TRIGGER TEMP_ALERT BEFORE INSERT ON TEMPERATURE
FOR EACH ROW
declare pid number;
begin
select o.pid into pid from observations o where o.ob_id=:new.ob_id;
if(:new.t_amt>102)then
insert into alerts values(alerts_sequence.nextval,:new.ob_id,'temperature','102','n',pid);
end if;
end;

CREATE TRIGGER PATIENT_INCREMENT_TRIGGER BEFORE INSERT ON PATIENTS
FOR EACH ROW
BEGIN
SELECT patient_sequence.nextval INTO :NEW.pid from dual;
END;

CREATE TRIGGER PAIN_ALERT BEFORE INSERT ON PAIN
FOR EACH ROW
declare pid number;
begin
select o.pid into pid from observations o where o.ob_id=:new.ob_id;
if(:new.pain_scale>7)then
insert into alerts values(alerts_sequence.nextval,:new.ob_id,'pain','7','n',pid);
end if;
end;

CREATE TRIGGER HP_TRIGGER BEFORE INSERT ON HEALTHPROFESSIONALS
FOR EACH ROW
begin
select hp_sequence.nextval into :new.hp_id from dual;
end;

CREATE TRIGGER BP_TRIGGER BEFORE INSERT ON BLOODPRESSURE
FOR EACH ROW
BEGIN
SELECT bp_sequence.nextval INTO :NEW.bp_id FROM dual;
END;

CREATE TRIGGER PAIN_TRIGGER BEFORE INSERT ON PAIN
FOR EACH ROW
BEGIN
SELECT pain_sequence.nextval INTO :NEW.pain_id FROM dual;
END;

CREATE TRIGGER BP_DIA_ALERT BEFORE INSERT ON BLOODPRESSURE
FOR EACH ROW
declare pid number;
begin
select o.pid into pid from observations o where o.ob_id=:new.ob_id;
if(:new.bp_dia>=90)then
insert into alerts values(alerts_sequence.nextval,:new.ob_id,'diastolic blood pressure','90','n',pid);
end if;
end;

CREATE TRIGGER BP_SYS_ALERT BEFORE INSERT ON BLOODPRESSURE
FOR EACH ROW
declare pid number;
begin
select o.pid into pid from observations o where o.ob_id=:new.ob_id;
if(:new.bp_sys>=140)then
insert into alerts values(alerts_sequence.nextval,:new.ob_id,'systolic blood pressure','140','n',pid);
end if;
end;

CREATE TRIGGER DIET_TRIGGER BEFORE INSERT ON DIET
FOR EACH ROW
BEGIN
SELECT diet_sequence.nextval INTO :NEW.d_id FROM dual;
END;

CREATE TRIGGER ET_TRIGGER BEFORE INSERT ON EXERCISETOLERANCE
FOR EACH ROW
BEGIN
SELECT exercisetolerance_sequence.nextval INTO :NEW.et_id FROM dual;
END;

CREATE TRIGGER TEST_TRIGGER BEFORE INSERT ON TEST
FOR EACH ROW
begin
select test_sequence.nextval into :new.id from dual;
end;

